// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtffCzILx5IUTrg8LC1b8mOsltY7EHIdM',
    appId: '1:903178109798:web:860d9c136c6745023dfea7',
    messagingSenderId: '903178109798',
    projectId: 'chatapp-4b4e2',
    authDomain: 'chatapp-4b4e2.firebaseapp.com',
    storageBucket: 'chatapp-4b4e2.appspot.com',
    measurementId: 'G-Z7R16RLZ8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwuJDWYXbMXvW8DKOSX7WgN339KV90Qic',
    appId: '1:903178109798:android:ce22001c0c7554533dfea7',
    messagingSenderId: '903178109798',
    projectId: 'chatapp-4b4e2',
    storageBucket: 'chatapp-4b4e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDKm8_02SJnSNQaou16ga3_YZ5mGnkf0I',
    appId: '1:903178109798:ios:133388530241b6793dfea7',
    messagingSenderId: '903178109798',
    projectId: 'chatapp-4b4e2',
    storageBucket: 'chatapp-4b4e2.appspot.com',
    iosClientId: '903178109798-e97u6d388ul9hfg61g3nliks9u259m98.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDKm8_02SJnSNQaou16ga3_YZ5mGnkf0I',
    appId: '1:903178109798:ios:133388530241b6793dfea7',
    messagingSenderId: '903178109798',
    projectId: 'chatapp-4b4e2',
    storageBucket: 'chatapp-4b4e2.appspot.com',
    iosClientId: '903178109798-e97u6d388ul9hfg61g3nliks9u259m98.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
